const POS_ESQUERDA = 'Esquerda'
const POS_DIREITA = 'Direita'
const POS_CENTRO = 'Centro'

const TIPO_NAO_TERMINAL = 'NÃO TERMINAL'
const TIPO_TERMINAL = 'TERMINAL'
const TIPO_E = 'E'
const TIPO_NUMERO = 'NÚMERO'
const TIPO_INCOGNITA = 'INCÓGNITA'
const TIPO_OPERADOR = 'OPERADOR'
const TIPO_ABRE_PARENTESES = '('
const DESC_TIPO_ABRE_PARENTESES = 'ABRE PARÊNTESES'
const TIPO_FECHA_PARENTESES = ')'
const DESC_TIPO_FECHA_PARENTESES = 'FECHA PARÊNTESES'

const ARR_OPERADORES: Array<String> = ['+', '-', '/', '*']
const ARR_INCOGNITAS: Array<String> = ["x", "y"]

export { 
    POS_ESQUERDA, 
    POS_DIREITA, 
    POS_CENTRO,
    TIPO_NAO_TERMINAL,
    TIPO_TERMINAL,
    TIPO_E,
    TIPO_NUMERO,
    TIPO_INCOGNITA,
    TIPO_OPERADOR,
    TIPO_ABRE_PARENTESES,
    TIPO_FECHA_PARENTESES,
    ARR_OPERADORES,
    ARR_INCOGNITAS,
    DESC_TIPO_ABRE_PARENTESES,
    DESC_TIPO_FECHA_PARENTESES,
}